### PR TITLE
Fix installation instructions

### PR DESCRIPTION
**Pull request by khromov**
Related to the package name change in #1

### CODE REVIEW

**Comment by richardsweeney** [comment]
Tack @khromov vi missade detta på #1 och det finns ett kommentar där, men eftersom detta är egentligen stängt accepterar jag gärna detta! 😎

**Comment by pelmered** [comment]
Does this work @khromov?  
The package is still under the old vendor name on Packagist: https://packagist.org/packages/ac-components/composer-plugin-language-update

Maybe we have to re-add the project there @richardsweeney?

**Comment by pelmered** [comment]
Nope. Doesn't work.

`composer require Angrycreative/composer-plugin-language-update:"*"` gives:
```
  Problem 1
    - The requested package angrycreative/composer-plugin-language-update could not be found in any version, there may be a typo in the package name
```

**Comment by richardsweeney** [comment]
Jepp. Vi får ta och uppdatera package.json

**Comment by khromov** [comment]
@pelmered Sorry, the plugin didn't show up in the Packagist search so I assumed it wasn't published.

**Pull request merged**
